# Reference: STSW-STUSB004 Documentation
# Accession: G00084

import argparse
import asyncio

from glasgow.support import logging
from glasgow.applet.interface.i2c_controller import I2CNotAcknowledged, I2CControllerInterface
from glasgow.applet import GlasgowAppletV2


__all__ = ["StUsb4500NvmInterface", "I2CNotAcknowledged"]


class StUsb4500NvmInterface:
    def __init__(self, logger: logging.Logger, i2c_iface: I2CControllerInterface,
                 i2c_address: int = 0x28):
        self._logger = logger
        self._level  = logging.DEBUG if self._logger.name == __name__ else logging.TRACE

        self._i2c_iface   = i2c_iface
        self._i2c_address = i2c_address

    def _log(self, message, *args):
        self._logger.log(self._level, "stusb4500_nvm: " + message, *args)

    FTP_DATA_BASE = 0x53
    FTP_KEY       = 0x95
    FTP_CTRL_0    = 0x96
    FTP_CTRL_1    = 0x97

    FTP_KEY_VALUE = 0x47

    async def _read_regs(self, addr: int, length: int) -> list[int]:
        async with self._i2c_iface.transaction():
            await self._i2c_iface.write(self._i2c_address, [addr])
            chunk = await self._i2c_iface.read(self._i2c_address, length)
        self._log("reg-addr=%#04x read=<%s>", addr, chunk.hex())
        return list(chunk)

    async def _write_regs(self, addr: int, data: int | list[int]):
        if not isinstance(data, list):
            data = [data]
        self._log("reg-addr=%#04x write=<%s>", addr, bytes(data).hex())
        await self._i2c_iface.write(self._i2c_address, [addr, *data])

    async def _exec_cmd(self, cmd: int, c0_lsb: int = 0):
        await self._write_regs(self.FTP_CTRL_1, cmd)
        await self._write_regs(self.FTP_CTRL_0, 0x50 | c0_lsb)
        await asyncio.sleep(0.005)

    async def enable(self):
        await self._write_regs(self.FTP_KEY, self.FTP_KEY_VALUE)
        await self._write_regs(self.FTP_DATA_BASE, 0x00)
        await self._write_regs(self.FTP_CTRL_0, 0x40)
        await self._write_regs(self.FTP_CTRL_0, 0x00)
        await asyncio.sleep(0.001)
        await self._write_regs(self.FTP_CTRL_0, 0x40)

    async def disable(self):
        await self._write_regs(self.FTP_CTRL_0, [0x40, 0x00])
        await self._write_regs(self.FTP_KEY, 0x00)

    async def erase(self):
        await self._exec_cmd(0xFA)
        await self._exec_cmd(0x07)
        await self._exec_cmd(0x05)

    async def read_sector(self, sector: int) -> list[int]:
        await self._exec_cmd(0x00, c0_lsb=sector)
        return await self._read_regs(self.FTP_DATA_BASE, 8)

    async def write_sector(self, sector: int, data: list[int]):
        await self._write_regs(self.FTP_DATA_BASE, data)
        await self._exec_cmd(0x01)
        await self._exec_cmd(0x06, c0_lsb=sector)


class StUsb4500NvmApplet(GlasgowAppletV2):
    logger = logging.getLogger(__name__)
    help = "read and write STUSB4500 NVM"
    description = """
    Read and write the NVM inside the STUSB4500 USB-PD initiator.

    The file format used is the .txt generated by the STSW-STUSB002 GUI utility provided by ST.
    """

    @classmethod
    def add_build_arguments(cls, parser, access):
        access.add_voltage_argument(parser)
        access.add_pins_argument(parser, "scl", default=True, required=True)
        access.add_pins_argument(parser, "sda", default=True, required=True)

        def address(arg):
            return int(arg, 0)
        parser.add_argument(
            "-A", "--i2c-address", type=address, metavar="I2C-ADDR", default=0x28,
            help="I²C address of the STUSB4500; typically 0b0101000 "
                 "(default: 0x28)")

    def build(self, args):
        with self.assembly.add_applet(self):
            self.assembly.use_voltage(args.voltage)
            self.i2c_iface = I2CControllerInterface(self.logger, self.assembly,
                scl=args.scl, sda=args.sda)
            self.stusb4500_iface = StUsb4500NvmInterface(self.logger, self.i2c_iface,
                args.i2c_address)

    async def setup(self, args):
        await self.i2c_iface.clock.set_frequency(100e3)

    @classmethod
    def add_run_arguments(cls, parser):
        p_operation = parser.add_subparsers(dest="operation", metavar="OPERATION", required=True)

        p_read = p_operation.add_parser(
            "read", help="read NVM")
        p_read.add_argument(
            "-f", "--file", metavar="FILENAME", type=argparse.FileType("w"),
            help="write NVM contents to FILENAME")

        p_write = p_operation.add_parser(
            "write", help="write NVM")
        p_write.add_argument(
            "-f", "--file", metavar="FILENAME", type=argparse.FileType("r"),
            help="write NVM with contents of FILENAME")

    def _read_data_file(self, fh):
        data = {}
        for l in fh.readlines():
            if l.startswith("0x"):
                a = int(l[0:4], 16)
                d = [int(x, 16) for x in l[5:].split()]
                data[a] = d
        return data

    def _write_data_file(self, fh, data):
        for a in sorted(data.keys()):
            fh.write(f"0x{a:02X}:\t" + "\t".join([f"0x{x:02X}" for x in data[a]]) + "\t\r\n")
        fh.write("\r\n")
        fh.write("# NVM memory map : STUSBxx \r\n")
        fh.write("\r\n")

    async def run(self, args):
        if args.operation == "read":
            await self.stusb4500_iface.enable()

            data = {}
            for sector in range(5):
                data[0xC0 + 8 * sector] = await self.stusb4500_iface.read_sector(sector)

            await self.stusb4500_iface.disable()

            self._write_data_file(args.file, data)

        if args.operation == "write":
            data = self._read_data_file(args.file)

            await self.stusb4500_iface.enable()
            await self.stusb4500_iface.erase()

            for sector in range(5):
                k = 0xC0 + 8 * sector
                if k not in data:
                    continue

                await self.stusb4500_iface.write_sector(sector, data[k])

            await self.stusb4500_iface.disable()

    @classmethod
    def tests(cls):
        from . import test
        return test.StUsb4500NvmAppletTestCase
