M48
; DRILL file KiCad 10.0.5+dfsg-1 date 2026-09-25T10:13:51
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2026-09-25T10:13:51+00:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,10.0.5+dfsg-1
; #@! TF.FileFunction,NonPlated,1,6,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.600
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C0.650
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T3C3.700
%
G90
G05
T1
X147.3Y-99.9
X147.3Y-116.5
T2
X122.05Y-105.31
X122.05Y-111.09
T3
X186.3Y-108.2
M30
