on:
  push:
  pull_request:
  merge_group:

name: CI
jobs:

  lint-software:
    runs-on: ubuntu-latest
    steps:
      - name: Check out source code
        uses: actions/checkout@v4
      - name: Check source code for issues
        uses: astral-sh/ruff-action@v3
        with:
          # `noqa:` directives are intentionally ignored; see `ruff.toml`
          args: check --ignore-noqa --fix --no-show-fixes
          src: software/

  test-software:
    strategy:
      matrix:
        os-version:
        - ubuntu-24.04
        python-version:
        - '3.13.x'
        - '3.14.x'
        - 'pypy-3.11'
        dep-versions:
        - minimal
        - latest
        allow-failure:
        - false
        include:
        - os-version: ubuntu-24.04
          python-version: '3.15-dev'
          dep-versions: minimal
          allow-failure: true
        - os-version: ubuntu-24.04
          python-version: '3.15-dev'
          dep-versions: latest
          allow-failure: true
    continue-on-error: ${{ matrix.allow-failure }}
    runs-on: ${{ matrix.os-version }}
    name: 'test-software (${{ matrix.python-version }}, deps: ${{ matrix.dep-versions }})'
    env:
      PDM_LOCKFILE: ${{ matrix.dep-versions == 'minimal' && 'pdm.min.lock' || 'pdm.lock' }}
    steps:
      - name: Install native dependencies for Pillow
        if: ${{ contains(matrix.python-version, '-dev') }}
        run: |
          sudo apt-get update
          sudo apt-get install libjpeg8-dev zlib1g-dev
      - name: Check out source code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Cache Glasgow build products
        uses: actions/cache@v4
        with:
          path: ~/.cache/GlasgowEmbedded
          key: Glasgow-${{ matrix.python-version }}-${{ matrix.dep-versions }}-${{ hashFiles('./software/**') }}
          restore-keys: |
            Glasgow-${{ matrix.python-version }}-${{ matrix.dep-versions }}-
            Glasgow-${{ matrix.python-version }}-
            Glasgow-
      - name: Set up PDM
        uses: pdm-project/setup-pdm@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Generate lockfile
        working-directory: ./software
        run: pdm lock --group :all ${{ matrix.dep-versions == 'minimal' && '--strategy direct_minimal_versions' || '' }}
      - name: Verify lockfile matches checked-in version
        if: matrix.dep-versions == 'minimal'
        working-directory: ./software
        run: git diff --exit-code pdm.min.lock
      - name: Cache PDM package data
        uses: actions/cache@v4
        with:
          path: ~/.cache/pdm
          key: PDM-${{ matrix.dep-versions }}-${{ hashFiles(format('./software/{0}', env.PDM_LOCKFILE)) }}
          restore-keys: |
            PDM-${{ matrix.dep-versions }}-
            PDM-
      - name: Cache virtual environment
        uses: actions/cache@v4
        with:
          path: ~/.cache/pdm
          key: venv-${{ runner.os }}-${{ matrix.python-version }}-${{ matrix.dep-versions }}-${{ hashFiles(format('./software/{0}', env.PDM_LOCKFILE)) }}
          restore-keys: |
            venv-${{ runner.os }}-${{ matrix.python-version }}-${{ matrix.dep-versions }}-
            venv-${{ runner.os }}-${{ matrix.python-version }}-
      - name: Install dependencies
        working-directory: ./software
        run: pdm sync
      - name: Cache YoWASP build products
        uses: actions/cache@v4
        with:
          path: ~/.cache/YoWASP
          key: YoWASP-${{ runner.os }}-${{ matrix.python-version }}-${{ matrix.dep-versions }}-${{ hashFiles('./software/.venv/**/*.wasm') }}
          restore-keys: |
            YoWASP-${{ runner.os }}-${{ matrix.python-version }}-${{ matrix.dep-versions }}-
            YoWASP-${{ runner.os }}-${{ matrix.python-version }}-
            YoWASP-${{ runner.os }}-
      - name: Run tests
        working-directory: ./software
        run: |
          pdm run glasgow --help
          pdm run glasgow build --rev C3 uart
          pdm run test --verbose

  build-firmware:
    runs-on: ubuntu-latest
    steps:
      - name: Check out source code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          submodules: recursive
      - name: Build and deploy firmware
        working-directory: ./software
        run: |
          ./deploy-firmware.sh
      - name: Check if the checked-in firmware is modified
        id: is_modified
        uses: tj-actions/changed-files@v46
        with:
          files: |
            software/glasgow/hardware/firmware.ihex
      - name: Verify firmware matches checked-in version
        if: steps.is_modified.outputs.any_changed == 'true'
        run: git diff --exit-code --text software/glasgow/hardware/firmware.ihex

  build-manual:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: docs/manual
    steps:
      - name: Check out source code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Set up PDM
        uses: pdm-project/setup-pdm@v4
      - name: Install dependencies
        run: pdm install
      - name: Build documentation
        env:
          DOCS_IS_PRODUCTION: ${{ (github.repository == 'GlasgowEmbedded/glasgow' && github.event.ref == 'refs/heads/main') && 'yes' || 'no' }}
        run: |
          pdm run build
          pdm run build-zh
      - name: Upload documentation archive (en_US)
        uses: actions/upload-artifact@v4
        with:
          name: docs-en
          path: docs/manual/build
      - name: Upload documentation archive (zh_CN)
        uses: actions/upload-artifact@v4
        with:
          name: docs-zh
          path: docs/manual/build-zh

  build-wheel:
    runs-on: ubuntu-latest
    steps:
      - name: Check out source code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Build wheel
        run: |
          pip install build
          python -m build --wheel software/
      - name: Upload wheel
        uses: actions/upload-artifact@v4
        with:
          name: wheel
          path: software/dist/

  required: # group all required workflows into one to avoid reconfiguring this in Actions settings
    needs:
      # - lint-software
      - test-software
      - build-firmware
      - build-manual
    if: ${{ always() && !contains(needs.*.result, 'cancelled') }}
    runs-on: ubuntu-latest
    steps:
      - run: ${{ contains(needs.*.result, 'failure') && 'false' || 'true' }}

  publish-manual:
    needs:
      - build-manual
      - build-wheel
    if: ${{ github.repository == 'GlasgowEmbedded/glasgow' && github.event.ref == 'refs/heads/main' }}
    runs-on: ubuntu-latest
    steps:
      - name: Download git-pages-cli
        run: |
          curl -o git-pages-cli https://codeberg.org/git-pages/git-pages-cli/releases/download/latest/git-pages-cli.linux-amd64
          chmod +x git-pages-cli
      - name: Download documentation from artifact (en)
        uses: actions/download-artifact@v4
        with:
          name: docs-en
          path: pages/en/
      - name: Download documentation from artifact (zh)
        uses: actions/download-artifact@v4
        with:
          name: docs-zh
          path: pages/zh/
      - name: Download wheel
        uses: actions/download-artifact@v4
        with:
          name: wheel
          path: wheel
      - name: Inject wheel
        run: |
          mkdir -p pages/dist/
          cp wheel/*.whl pages/dist/glasgow-0.1.dev0-py3-none-any.whl
      - name: Set up redirects (en)
        run: |
          cat >pages/_redirects <<END
          //www.glasgow-embedded.org/* //glasgow-embedded.org/:splat 301!
          //glasgowembedded.org/* //glasgow-embedded.org/:splat 301!
          //www.glasgowembedded.org/* //glasgow-embedded.org/:splat 301!
          //glasgow-embedded.com/* //glasgow-embedded.org/:splat 301!
          //www.glasgow-embedded.com/* //glasgow-embedded.org/:splat 301!
          //glasgowembedded.com/* //glasgow-embedded.org/:splat 301!
          //www.glasgowembedded.com/* //glasgow-embedded.org/:splat 301!

          /latest/dist/* /dist/:splat 301
          /latest/* /en/:splat 301
          / /en/intro.html 302!
          END
      - name: Publish website (en)
        run: |
          ./git-pages-cli https://glasgow-embedded.org/ --upload-dir pages/ --password ${{ secrets.PAGES_TOKEN }}
          ./git-pages-cli https://www.glasgow-embedded.org/ --upload-dir pages/ --password ${{ secrets.PAGES_TOKEN }}
      - name: Set up redirects (zh)
        run: |
          cat >pages/_redirects <<END
          //www.glasgow-embedded.cn/* //glasgow-embedded.cn/:splat 301!

          / /zh/intro.html 302!
          END
      - name: Publish website (zh)
        run: |
          ./git-pages-cli https://glasgow-embedded.cn/ --upload-dir pages/ --password ${{ secrets.PAGES_CN_TOKEN }}
          ./git-pages-cli https://www.glasgow-embedded.cn/ --upload-dir pages/ --password ${{ secrets.PAGES_CN_TOKEN }}
